spring:
  application:
    name: example-ot
opentracing:
  jaeger:
    enable-b3-propagation: true
---
spring:
  profiles: local
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
