spring:
  application:
    name: example-ot
opentracing:
  jaeger:
    enable-b3-propagation: true
    udp-sender:
      host: localhost
      port: 6831
---
spring:
  profiles: local
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
---
spring:
- profiles: udp
 opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
