spring:
  application:
    name: example-ot
opentracing:
  jaeger:
    enable-b3-propagation: true
---
spring:
  profiles: local
opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector-demo.apps-rp.cloudteco.com.ar:14268/api/traces
