apiVersion: v1
kind: Template
metadata:
  name: spring-boot-tracing-template
annotations:
    description: "A SpringBoot microservice which sends distributed traces to a side car Jaeger Agent"
    tags: "tracing,distributed" # TODO : Refer to the id and categoryAliases in CATALOG_CATEGORIES in the console’s constants file.
# Parameters
parameters:
- name: JAEGER_COLLECTOR_URL
  description: The URL addresss of the Jaeger Collector where traces are send by the Jaeger Agent
  value: jaeger-collector.jaeger.svc:14267
  required: true
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-exec.jar'
  required: true
# Objects defined for the template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: spring-boot-tracing
      group: dev.snowdrop.example
      version: 1.0-SNAPSHOT
    name: spring-boot-tracing
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-tracing
      group: dev.snowdrop.example
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: spring-boot-tracing
      group: dev.snowdrop.example
      version: 1.0-SNAPSHOT
    name: spring-boot-tracing
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: spring-boot-tracing
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spring-boot-tracing
      group: dev.snowdrop.example
      version: 1.0-SNAPSHOT
    name: spring-boot-tracing
  spec:
    replicas: 1
    selector:
      app: spring-boot-tracing
      group: dev.snowdrop.example
      version: 1.0-SNAPSHOT
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: spring-boot-tracing
          group: dev.snowdrop.example
          version: 1.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: spring-boot-tracing:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
        - command:
          - /go/bin/agent-linux
          - --collector.host-port=${JAEGER_COLLECTOR_URL}
          image: jaegertracing/jaeger-agent
          imagePullPolicy: Always
          name: jaeger-agent
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 5778
            protocol: TCP
          - containerPort: 6831
            name: ambit-lm
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-tracing:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: spring-boot-tracing-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: spring-boot-tracing:latest
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_COPY_ARGS
          value: '*-exec.jar'
        from:
          kind: ImageStreamTag
          name: runtime:latest
      type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: spring-boot-tracing
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jaeger-agent
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: jaegertracing/jaeger-agent
